### ISSUE TITLE
tracking cors 1.0 promotion

### ISSUE THREAD

**Issue by robjtede** [actix/actix-extras#115]
Should be pretty easy to get actix-cors in a 1.0 state since it's feature complete.

- [x] panic on wildcard origin #114
- [x] clean up docs about when panic occurs
- [x] consider removing CorsFactory #119
- [x] address any other open issues
- [x] is disable_preflight needed?
  - im sure someone out there has a use case
  - could consider adding a deprecation notice in v1 asking anyone with a use case can open an issue
- [x] is send_wildcard needed?
  - we'll leave it but it's not very useful in today's web world
- [x] allowed_origin_fn without allowed_origin bug fixed in #119
- [x] pass origin header down as parameter to allow origin fns (+ optimise origin extraction) [#120]
- [x] should CorsError be public?
  - there is probably a use case somewhere for wanting to manually return these error, in which case having the pre-built ErrorResponse impls could be useful.

**Comment by lucab** [comment]
@robjtede if you are open to breaking changes, these are a few things I'd like to see happening before 1.0:
 * `Cors` is a builder, it should have a `Builder` or `Config` suffix in its name
 * `Cors::finish()` should return a `Result` (and most other methods should not panic
 * `Cors::default()` really is `CorsFactory::default()`, and it should try to use the same default config
 * `CorsFactory` is a middleware (and I use it, not sure it can be removed), which makes it confusing with `CorsMiddleware`
 * `AllOrSome` does not seem to be used in the public interface (it may be kept private?)
 * ` CorsError` does not implement std:error::Error

In general I'd be happy to tackle most of those, but most are quite invasive API changes so I'd like to get feedback first.

**Comment by robjtede** [comment]
> Cors is a builder, it should have a Builder or Config suffix in its name

I would usually agree with you on the builder suffix. However, the pattern for middleware (see [`actix_web::middleware`](https://docs.rs/actix-web/3.1.0/actix_web/middleware/index.html)) is that the "builders" are `Xyz` (impls Transform) and the middlewares are `XyzMiddleware` (impls Service). For the same reason, I suspect a refactor could be done remove the `CorsFactory` (which exists only to impl Transform).

---

> Cors::finish() should return a Result (and most other methods should not panic)

Hopefully, `Cors::finish()` is not required. I'd be interested to see which panics you convert into errors. Some panics are acceptable since middleware is a startup task.

---

> AllOrSome does not seem to be used in the public interface (it may be kept private?)

Yep, sounds good.

---

> CorsError does not implement std:error::Error

Definitely should.
